<A HREF="/AdvWorks/equipment/default.asp">
<IMG SRC="/AdvWorks/multimedia/images/icon_sub_equipment.GIF" ALIGN=CENTER WIDTH=85 HEIGHT=45 BORDER=0 ALT="Order Your Equipment"></A><BR>

<A HREF="/AdvWorks/excursions/default.asp">
<IMG SRC="/AdvWorks/multimedia/images/icon_sub_excursions.GIF" ALIGN=CENTER WIDTH=85 HEIGHT=45 BORDER=0 ALT="Excursions"></A><BR>

<A HREF="/AdvWorks/resources/default.asp">
<IMG SRC="/AdvWorks/multimedia/images/icon_sub_resources.GIF" ALIGN=CENTER WIDTH=85 HEIGHT=45 BORDER=0 ALT="Resources"></A><BR>

<A HREF="/AdvWorks/internal/default.asp">
<IMG SRC="/AdvWorks/multimedia/images/icon_sub_internal.GIF" ALIGN=CENTER WIDTH=85 HEIGHT=45 BORDER=0 ALT="Internal"></A><BR>

<A HREF="/AdvWorks/default.asp">
<IMG SRC="/AdvWorks/multimedia/images/icon_sub_home.GIF" ALIGN=CENTER WIDTH=85 HEIGHT=45 BORDER=0 ALT="Home"></A>
<BR>
<!--#include virtual="/AdvWorks/srcform.inc"-->
<BR>

<% If Session("ItemCount") > 0 Then %>
     <A HREF="/AdvWorks/equipment/check_out.asp">
     <IMG SRC="/AdvWorks/multimedia/images/checkout.gif" WIDTH=85 HEIGHT=45 ALT="Check Out" BORDER=O></A>
<% End If %>

