<A HREF="/AdvWorks/equipment/default.asp">
<IMG SRC="/AdvWorks/multimedia/images/icon_sub_equipment.GIF" WIDTH="85" HEIGHT="45" BORDER=0 ALT="Equipment"></A><BR>

<IMG SRC="/AdvWorks/multimedia/images/sidebar_text.gif" WIDTH="122" HEIGHT="202" BORDER=0 USEMAP="#SIDEBAR" ALT="Items for Sale">

<BR>

<MAP NAME="SIDEBAR">
<AREA SHAPE="RECT" COORDS="0,0, 99,18"     HREF="/AdvWorks/equipment/catalog_type.asp?ProductType=carabiner">
<AREA SHAPE="RECT" COORDS="0,19, 101,35"   HREF="/AdvWorks/equipment/catalog_type.asp?ProductType=crampon">
<AREA SHAPE="RECT" COORDS="0,36, 101,51"   HREF="/AdvWorks/equipment/catalog_type.asp?ProductType=harness">
<AREA SHAPE="RECT" COORDS="0,52, 100,66"   HREF="/AdvWorks/equipment/catalog_type.asp?ProductType=RockShoes">
<AREA SHAPE="RECT" COORDS="0,67, 101,82"   HREF="/AdvWorks/equipment/catalog_type.asp?ProductType=backpack">
<AREA SHAPE="RECT" COORDS="0,83, 99,99"    HREF="/AdvWorks/equipment/catalog_type.asp?ProductType=SleepingBag">
<AREA SHAPE="RECT" COORDS="0,100, 100,113" HREF="/AdvWorks/equipment/catalog_type.asp?ProductType=supplies">
<AREA SHAPE="RECT" COORDS="0,114, 101,130" HREF="/AdvWorks/equipment/catalog_type.asp?ProductType=tent">
<AREA SHAPE="RECT" COORDS="0,131, 100,147" HREF="/AdvWorks/equipment/catalog_type.asp?ProductType=boot">
<AREA SHAPE="RECT" COORDS="0,148, 102,162" HREF="/AdvWorks/equipment/catalog_type.asp?ProductType=parka">
<AREA SHAPE="RECT" COORDS="0,163, 101,179" HREF="/AdvWorks/equipment/catalog_type.asp?ProductType=pants">
<AREA SHAPE="RECT" COORDS="0,180, 101,198" HREF="/AdvWorks/equipment/catalog_type.asp?ProductType=shirt">
</MAP>

<A HREF="/AdvWorks/default.asp">
<IMG SRC="/AdvWorks/multimedia/images/icon_sub_home.GIF" WIDTH="85" HEIGHT="45" ALIGN=CENTER BORDER=0 ALT="Home"></A>
<BR>